### ISSUE TITLE
repository not found.

### ISSUE THREAD

**Issue by amariscal1** [sidhantpanda/raspberry-pi-home-backend#1]
I get 
remote: Repository not found 
every time i try to clone

**Comment by amariscal1** [comment]
fixed by  cloning this way:
git clone https://githubusername:password@github.com/sidhandpanda/raspberry-pi-home-backend.git

**Comment by sidhantpanda** [comment]
@amariscal1 you can also add your SSH key to your Github account so that you can clone via SSH.
